// Purchase menu buttons: Driver, Gunner, Commander, Crew, Open, Locked
enum CTI_PurchaseInfos
{
	EMPTY_OPEN,
	EMPTY_LOCKED,
	
	DRIVER_OPEN,
	DRIVER_LOCKED,
	
	GUNNER_OPEN,
	GUNNER_LOCKED,
	
	COMMANDER_OPEN,
	COMMANDER_LOCKED,
	
	CREW_OPEN,
	CREW_LOCKED,

	DRIVER_GUNNER_OPEN,
	DRIVER_GUNNER_LOCKED,
	
	DRIVER_COMMANDER_OPEN,
	DRIVER_COMMANDER_LOCKED,
	
	DRIVER_CREW_OPEN,
	DRIVER_CREW_LOCED,
	
	DRIVER_GUNNER_COMMANDER_OPEN,
	DRIVER_GUNNER_COMMANDER_LOCKED,
	
	DRIVER_GUNNER_COMMANDER_CREW_OPEN,
	DRIVER_GUNNER_COMMANDER_CREW_LOCKED,

	DRIVER_GUNNER_CREW_OPEN,
	DRIVER_GUNNER_CREW_LOCKED,

	DRIVER_COMMANDER_CREW_OPEN,
	DRIVER_COMMANDER_CREW_LOCKED,

	GUNNER_COMMANDER_OPEN,
	GUNNER_COMMANDER_LOCKED,

	GUNNER_CREW_OPEN,
	GUNNER_CREW_LOCKED,

	GUNNER_COMMANDER_CREW_OPEN,
	GUNNER_COMMANDER_CREW_LOCKED,

	COMMANDER_CREW_OPEN,
	COMMANDER_CREW_LOCKED
};